name: GH Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          lfs: true
          persist-credentials: false

      - name: Install & Build
        run: |
          npm ci
          PUBLIC_PATH=./ npm run build

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          clean: true
